const express = require('express');
const cors = require('cors');
require('dotenv').config();

const authRoutes = require('./routes/auth');
const assetRoutes = require('./routes/assets');

const app = express();
app.use(cors());
app.use(express.json());

// Mount Routes
app.use('/auth', authRoutes);
app.use('/assets', assetRoutes);

// Admin Role Assignment
app.post('/admin/roles/assign', (req, res) => {
    // Logic to verify caller is ADMIN, then call roleToken.mintRole()
    res.json({ status: "role_assigned" });
});

// SOC Copilot feed
app.get('/soc/alerts', (req, res) => {
    // In production, this would query the DB for alerts generated by the UEBA service
    res.json({ alerts: [] });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`ArgusChain Node API listening on port ${PORT}`);
});
